[package]
name = "tshirt_co"
version = "0.1.0"
edition = "2021"
description = "a library for tshirt inventory tracking, handle giveaway thshirts"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
